on: 
  push
name: Test
jobs:
  test:
    name: Testa
    runs-on: macOS-latest
    strategy:
        matrix:
          xcode: [11.2_beta 2]
          destination: ['platform=iOS Simulator,name=iPhone 11']
    steps:
      - run: swift --version
      - name: Checkout
        uses: actions/checkout@master
      - name: Cache Cocoapods
        id: cache-cocoapods
        uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods_cache-
          restore-keys: |
            ${{ runner.os }}-pods_cache-
      - name : Pod install Check
        if: steps.cache-cocoapods.outputs.cache-hit != 'true'
        run: |
          bundle install; bundle exec pod install;
